Repository st-baonguyen/FE-Internship-2021_Bao-Nguyen_FE-Exercise, pull requests merged in 2021-05, with the labels that each got.

#48 [E-shop-cart][HTML+SCSS] Create button add to cart
  excercise-e-shop/home.html
Labels: need to reviewed

#50 [E-shop-cart][Js] Add event for cart page
  excercise-e-shop/cart.html
  excercise-e-shop/sass/components/_product.scss
  excercise-e-shop/sass/layout/_banner.scss
  excercise-e-shop/sass/layout/_footer.scss
  excercise-e-shop/sass/layout/_header.scss
  excercise-e-shop/sass/modules/_button.scss
  excercise-e-shop/sass/pages/_cart.scss
  excercise-e-shop/sass/pages/_home.scss
  excercise-e-shop/sass/pages/_style.scss
  excercise-e-shop/scripts/addToCart.js
  excercise-e-shop/scripts/cart.js
  excercise-e-shop/style/style.css
Labels: need to reviewed

#51 [Event-carrt][Js] Convert ES5 -> ES6
  excercise-e-shop/cart.html
  excercise-e-shop/home.html
  excercise-e-shop/scripts/addToCart.js
  excercise-e-shop/scripts/cart.js
  excercise-e-shop/scripts/common.js
Labels: need to reviewed

#53 [Research] SSR-CSR-SPA-PWA-MPA
  exercise_js/research/README.md
Labels: documentation, done

#20 [ExerciseJS] Answer the question and complete exercise
  exercise_js/README.md
  exercise_js/caculatorAge/calculatorAge.js
  exercise_js/index.js
  exercise_js/research/README.md
  exercise_js/show-plan/showPlan.css
  exercise_js/show-plan/showPlan.html
  exercise_js/show-plan/showPlan.js
Labels: documentation, done

#21 [ExerciseJS] Sync and Async
  async_sync/README.md
  async_sync/assets/2.PNG
  async_sync/assets/3.PNG
  async_sync/assets/5.PNG
  async_sync/assets/6.PNG
  async_sync/assets/7.PNG
  async_sync/assets/8.PNG
  async_sync/assets/step0.PNG
Labels: documentation, done

#24 [ExerciseJS] Create UI with DOM
  exercise_js/domJs/dom.html
  exercise_js/domJs/script.js
  exercise_js/domJs/style.css
Labels: done
